services:
  - name: jcmarket
    type: web
    runtime: static
    rootDir: JCMarket-ts
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        value: 489109189204-q3v366mm8ed5sht13bn7ra7vpqf1ujtn.apps.googleusercontent.com
      - key: VITE_API_URL
        value: "https://jcmarketbackend.onrender.com"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://jcmarketbackend.onrender.com/api/*
      - type: rewrite
        source: /images/*
        destination: https://jcmarketbackend.onrender.com/images/*
      - type: rewrite
        source: /*
        destination: /index.html

  - name: jcmarketbackend

    type: web
    runtime: node
    rootDir: ecommerce-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        value: 489109189204-q3v366mm8ed5sht13bn7ra7vpqf1ujtn.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_IDS
        value: 489109189204-q3v366mm8ed5sht13bn7ra7vpqf1ujtn.apps.googleusercontent.com
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ADMIN_EMAILS
        value: thegames-ye.online@gmail.com
      - key: FRONTEND_URL
        value: https://jcmarket.onrender.com
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        value: "false"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "true"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_TLS_REJECT_UNAUTHORIZED
        value: "true"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
